apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dummy-metis
  name: metis
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: dummy-metis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dummy-metis
    spec:
      containers:
      - image: docker.io/alisdairvravn/dummy-metis:1.0
        name: dummy-metis
        ports:
        - containerPort: 11027
      imagePullSecrets:
      - name: dockerhub